name: Update Allsvenskan Chart

on:
  schedule:
    # Körs kl 18:00 varje dag (UTC)
    # Justera till '0 16 * * *' om du vill ha kl 18 svensk tid pga sommartid
    - cron: '0 18 * * *'
  workflow_dispatch: # Gör att du kan starta skriptet manuellt under fliken Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pillow atproto

      - name: Run PPM script
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: python script.py
